package net.jfabricationgames.gdx.event;

public enum EventType {
	
	GAME_START, //
	PLAYER_RESPAWNED, //
	OUT_OF_AMMO, //
	EVENT_OBJECT_TOUCHED, //
	EVENT_ITEM_PICKED_UP, //
	TAKE_PLAYERS_COINS, //
	SHOW_IN_GAME_SHOP_MENU, //
	PLAYER_BUY_ITEM, //
	FAST_TRAVEL_POINT_REGISTERED, //
	FAST_TRAVEL_POINT_ENABLED, //
}
