package net.jfabricationgames.gdx.event;

public enum EventType {
	
	GAME_START, //
	GAME_LOADED, //
	PLAYER_RESPAWNED, //
	MAP_ENTERED, //
	OUT_OF_AMMO, //
	EVENT_OBJECT_TOUCHED, //
	EVENT_ITEM_PICKED_UP, //
	TAKE_PLAYERS_COINS, //
	SHOW_IN_GAME_SHOP_MENU, //
	PLAYER_BUY_ITEM, //
	FAST_TRAVEL_POINT_REGISTERED, //
	FAST_TRAVEL_POINT_ENABLED, //
	FAST_TRAVEL_TO_MAP_POSITION, //
	START_CUTSCENE, //
	CUTSCENE_EVENT, //
	ON_SCREEN_TEXT_ENDED, //
	CHANGE_MAP, // 
	SET_ITEM, //
	NPC_INTERACTION, //
	CUTSCENE_PLAYER_CHOICE, //
	CUTSCENE_CONDITION, //
	UPDATE_MAP_OBJECT_STATES, //
	QUICKSAVE, //
	AI_TEAM_CALL, //
}
